[workspace]
members = ["crates/*"]
resolver = "3"
[workspace.dependencies]
tokio = { version = "1.44.1", features = ["full"] }
trait-variant = "0.1.2"

[workspace.package]
authors = ["liblaf <30631553+liblaf@users.noreply.github.com>"]
edition = "2024"
version = "0.0.0"
